import { color } from '@/styles/color.css';

export const FLAVOR_DATA = {
  fruity: {
    name: '과일',
    color: color.flavor.fruity,
    items: [
      '사과',
      '딸기',
      '자몽',
      '레몬',
      '오렌지',
      '블렉베리',
      '라즈베리',
      '블루베리',
      '스트로베리',
      '건포도',
      '자두',
      '코코넛',
      '체리',
      '석류',
      '파인애플',
      '포도',
      '복숭아',
      '배',
      '라임',
    ] as string[],
  },
  floral: {
    name: '꽃',
    color: color.flavor.floral,
    items: ['장미', '자스민', '라일락', '홍차', '카모마일', '플로럴', '꽃'] as string[],
  },
  sweet: {
    name: '달콤한',
    color: color.flavor.sweet,
    items: [
      '카라멜',
      '초콜릿',
      '바닐라',
      '꿀',
      '다크 초콜릿',
      '당밀',
      '메이플 시럽',
      '바닐라 첨가향',
      '전반적으로 달콤한',
      '달콤한 향료',
    ] as string[],
  },
  spices: {
    name: '향신료',
    color: color.flavor.spices,
    items: ['후추', '톡 쏘는', '아니스', '넛맥', '계피', '정향'] as string[],
  },
  roasted: {
    name: '구운',
    color: color.flavor.roasted,
    items: [
      '구운 호두',
      '파이프 담배',
      '담배',
      '아린',
      '재',
      '연기',
      '노릇하게 구운',
      '곡물',
      '맥아',
    ] as string[],
  },
  green: {
    name: '그린',
    color: color.flavor.green,
    items: [
      '허브',
      '신선한',
      '건초같은',
      '야채맛',
      '암녹색',
      '완두콩',
      '덜 익은',
      '거친',
      '올리브유',
    ] as string[],
  },
  sour: {
    name: '시큼',
    color: color.flavor.sour,
    items: [
      '신 향료',
      '아세트산',
      '부티르산',
      '이소발레르산',
      '구연산',
      '사과산',
      '와인',
      '위스키',
      '발효된',
      '지나치게 익은',
    ] as string[],
  },
  nutty: {
    name: '견과',
    color: color.flavor.nutty,
    items: ['아몬드', '땅콩', '헤이즐넛', '초콜릿', '다크 초콜릿'] as string[],
  },
} as const;
