import type { Metadata } from "next";
import "./globals.css";
import { rootContainer } from "./layout.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={rootContainer}>{children}</div>
      </body>
    </html>
  );
}
